project:
  type: website
  output-dir: ../docs  

website:
  title: "London SDE/AIC Technical Documentation"
  navbar:
    logo: media/logo_aic.png  
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
      - section: "MAIN"
        contents: 
          - href: index.qmd
            text: Home
      - section: "DATA PIPELINE"
        contents: 
          - href: pages/data_pipeline/intro.qmd
            text: Intro to Pipeline             
      - section: "COMMON DATA MODEL"
        contents: 
          - href: pages/data_model/intro.qmd
            text: Intro to CDM         
          - href: pages/data_model/cdm_person.qmd
            text: Table/PERSON
          - href: pages/data_model/cdm_condition_occurrence.qmd
            text: Table/CONDITION_OCCURRENCE
          - href: pages/data_model/cdm_drug_exposure.qmd
            text: Table/DRUG_EXPOSURE
#          - href: pages/data_model/cdm_measurement.qmd
#            text: Table/MEASUREMENT                        
                          
                     
format:
  html:
    theme: zephyr
    mermaid:
      theme: neutral
